"""
Agent-Based Wealth Simulation
==============================
Grid-based simulation where agents seek wealth-generating tiles.
- High-yield zone (darker green) gives +1 or +2 wealth/tick
- Outside: random -1, 0, or +1
- Agents with wealth < 0 for 3 consecutive ticks die
- Agents move greedily toward the high-yield zone

Requirements: pip install pygame numpy
Run: python wealth_simulation.py
"""

import pygame
import numpy as np
import random
import sys
from dataclasses import dataclass, field

# ── Configuration ─────────────────────────────────────────────────────────────
# All of these are color or geometry parameters that you can tweak to change the simulation's behavior and appearance.

COLS, ROWS = 22, 15
CELL = 36
WIN_W = COLS * CELL
WIN_H = ROWS * CELL + 120          # extra space for stats bar

FPS = 10                           # ticks per second (changeable at runtime)
N_AGENTS = 20

# High-yield zone (col_start, row_start, width, height)
HOT_X, HOT_Y, HOT_W, HOT_H = 10, 5, 7, 5

# Colors
BG_OUTSIDE     = (220, 230, 218)
BG_OUTSIDE_DIM = (200, 212, 198)
GRID_LINE      = (190, 205, 188)
HOT_CORE       = ( 26,  80,  50)   # darkest center
HOT_EDGE       = ( 56, 110,  75)   # lighter edge

AGENT_WELL     = ( 29, 158, 117)   # wealthy  ≥ 5
AGENT_MID      = (245, 196, 179)   # ok       0-4
AGENT_CRIT     = (226,  75,  74)   # critical < 0
AGENT_OUTLINE  = (255, 255, 255)

TEXT_COLOR     = ( 30,  30,  30)
PANEL_BG       = ( 42,  42,  42)
PANEL_TEXT     = (220, 220, 220)
PANEL_ACC      = ( 29, 158, 117)

# ── Tile yield logic ──────────────────────────────────────────────────────────

def tile_yield(col: int, row: int) -> int:
    """Return wealth generated by a tile this tick."""
    if HOT_X <= col < HOT_X + HOT_W and HOT_Y <= row < HOT_Y + HOT_H:
        cx = HOT_X + HOT_W / 2
        cy = HOT_Y + HOT_H / 2
        dist = ((col - cx) ** 2 + (row - cy) ** 2) ** 0.5
        max_dist = ((HOT_W / 2) ** 2 + (HOT_H / 2) ** 2) ** 0.5
        t = 1 - dist / max_dist
        return 2 if t > 0.65 else 1
    # Outside: -1 (20%), 0 (30%), +1 (50%)
    r = random.random()
    if r < 0.20: return -1
    if r < 0.50: return  0
    return 1


def tile_color(col: int, row: int) -> tuple:
    """Background color for a tile."""
    if HOT_X <= col < HOT_X + HOT_W and HOT_Y <= row < HOT_Y + HOT_H:
        cx = HOT_X + HOT_W / 2
        cy = HOT_Y + HOT_H / 2
        dist = ((col - cx) ** 2 + (row - cy) ** 2) ** 0.5
        max_dist = ((HOT_W / 2) ** 2 + (HOT_H / 2) ** 2) ** 0.5
        t = max(0.0, 1 - dist / max_dist)
        r = int(HOT_EDGE[0] + t * (HOT_CORE[0] - HOT_EDGE[0]))
        g = int(HOT_EDGE[1] + t * (HOT_CORE[1] - HOT_EDGE[1]))
        b = int(HOT_EDGE[2] + t * (HOT_CORE[2] - HOT_EDGE[2]))
        return (r, g, b)
    # Checkerboard outside for subtle texture
    return BG_OUTSIDE if (col + row) % 2 == 0 else BG_OUTSIDE_DIM


# ── Agent ─────────────────────────────────────────────────────────────────────

@dataclass # Using dataclass for convenience in defining the Agent class, which represents each individual in the simulation with their properties and behaviors.
class Agent:
    id: int
    col: int
    row: int
    wealth: int = 5
    neg_streak: int = 0
    dead: bool = False
    history: list = field(default_factory=list)   # wealth history

    def color(self) -> tuple:
        if self.wealth < 0:  return AGENT_CRIT # These three possible return values are defined in the configuration section at the top, and determine the color of the agent based on their current wealth.
        if self.wealth < 5:  return AGENT_MID
        return AGENT_WELL

    def choose_move(self) -> tuple:
        """Greedy: prefer tiles in the hot zone; add noise so they spread."""
        best_score = -1e9 # Start with a very low score to ensure any valid move will be better. The agent will evaluate all adjacent tiles (including diagonals) and calculate a score for each based on whether it's in the high-yield zone and some random noise to encourage exploration. The move with the highest score will be chosen.
        best = (self.col, self.row)
        for dc in (-1, 0, 1): # Loop through the possible column offsets (-1, 0, 1) to check the current tile and its immediate neighbors.
            for dr in (-1, 0, 1):
                nc = max(0, min(COLS - 1, self.col + dc))
                nr = max(0, min(ROWS - 1, self.row + dr))
                in_hot = HOT_X <= nc < HOT_X + HOT_W and HOT_Y <= nr < HOT_Y + HOT_H
                score = (2.5 if in_hot else 0) + random.random()
                if score > best_score:
                    best_score = score
                    best = (nc, nr)
        return best

    def step(self):
        if self.dead:
            return
        self.col, self.row = self.choose_move()
        gain = tile_yield(self.col, self.row)
        self.wealth += gain
        self.history.append(self.wealth)
        if self.wealth < 0:
            self.neg_streak += 1
        else:
            self.neg_streak = 0
        if self.neg_streak >= 3:
            self.dead = True


# ── Simulation state ──────────────────────────────────────────────────────────

class Simulation:
    def __init__(self, n_agents: int = N_AGENTS):
        self.tick = 0
        self.total_deaths = 0
        self.agents = [
            Agent(
                id=i,
                col=random.randint(0, COLS - 1),
                row=random.randint(0, ROWS - 1),
            )
            for i in range(n_agents)
        ]
        self.log: list[str] = ["Simulation started."]

    @property
    def alive(self):
        return [a for a in self.agents if not a.dead]

    @property
    def avg_wealth(self):
        al = self.alive
        return sum(a.wealth for a in al) / len(al) if al else 0

    def step(self):
        self.tick += 1
        for a in self.agents:
            was_dead = a.dead
            a.step()
            if not was_dead and a.dead:
                self.total_deaths += 1
                self.log.append(f"Tick {self.tick}: Agent {a.id} died (wealth {a.wealth}).")
        if not self.alive:
            self.log.append("All agents died.")

    def reset(self, n_agents: int = N_AGENTS):
        self.__init__(n_agents)


# ── Renderer ──────────────────────────────────────────────────────────────────

class Renderer:
    def __init__(self, sim: Simulation):
        pygame.init()
        self.screen = pygame.display.set_mode((WIN_W, WIN_H))
        pygame.display.set_caption("Agent Wealth Simulation")
        self.clock = pygame.time.Clock()
        self.font_sm  = pygame.font.SysFont("monospace", 11)
        self.font_med = pygame.font.SysFont("monospace", 13, bold=True)
        self.font_lg  = pygame.font.SysFont("monospace", 15, bold=True)
        self.sim = sim
        self.paused = True
        self.fps = FPS

    def draw_grid(self):
        for r in range(ROWS):
            for c in range(COLS):
                rect = pygame.Rect(c * CELL, r * CELL, CELL, CELL)
                pygame.draw.rect(self.screen, tile_color(c, r), rect)
                pygame.draw.rect(self.screen, GRID_LINE, rect, 1)

    def draw_agents(self):
        for a in self.sim.alive:
            cx = a.col * CELL + CELL // 2
            cy = a.row * CELL + CELL // 2
            pygame.draw.circle(self.screen, a.color(), (cx, cy), CELL // 2 - 3)
            pygame.draw.circle(self.screen, AGENT_OUTLINE, (cx, cy), CELL // 2 - 3, 2)
            label = self.font_sm.render(str(a.wealth), True, (255, 255, 255))
            self.screen.blit(label, label.get_rect(center=(cx, cy)))

    def draw_panel(self):
        panel = pygame.Rect(0, WIN_H - 120, WIN_W, 120)
        pygame.draw.rect(self.screen, PANEL_BG, panel)

        s = self.sim
        col_w = WIN_W // 4
        stats = [
            ("Tick",       str(s.tick)),
            ("Alive",      str(len(s.alive))),
            ("Deaths",     str(s.total_deaths)),
            ("Avg wealth", f"{s.avg_wealth:.1f}"),
        ]
        for i, (label, val) in enumerate(stats):
            x = i * col_w + 14
            lbl = self.font_sm.render(label.upper(), True, (150, 150, 150))
            self.screen.blit(lbl, (x, WIN_H - 112))
            val_surf = self.font_lg.render(val, True, PANEL_ACC)
            self.screen.blit(val_surf, (x, WIN_H - 95))

        # Controls hint
        hints = "[SPACE] pause/resume   [R] reset   [↑↓] speed   [Q] quit"
        hint_surf = self.font_sm.render(hints, True, (120, 120, 120))
        self.screen.blit(hint_surf, (14, WIN_H - 60))

        # Log (last 2 messages)
        for i, msg in enumerate(self.sim.log[-2:]):
            log_surf = self.font_sm.render(msg, True, (180, 180, 180))
            self.screen.blit(log_surf, (14, WIN_H - 40 + i * 16))

        # Speed indicator
        spd = self.font_sm.render(f"Speed: {self.fps} tps {'(paused)' if self.paused else ''}", True, (160, 160, 160))
        self.screen.blit(spd, (WIN_W - 180, WIN_H - 112))

    def draw_legend(self):
        items = [
            (AGENT_WELL, "Wealthy (≥5)"),
            (AGENT_MID,  "Struggling (0-4)"),
            (AGENT_CRIT, "Critical (<0)"),
        ]
        x = WIN_W - 200
        y = 8
        for color, label in items:
            pygame.draw.circle(self.screen, color, (x, y + 5), 6)
            pygame.draw.circle(self.screen, AGENT_OUTLINE, (x, y + 5), 6, 1)
            txt = self.font_sm.render(label, True, TEXT_COLOR)
            self.screen.blit(txt, (x + 12, y))
            y += 18

    def run(self):
        running = True
        while running:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    running = False
                elif event.type == pygame.KEYDOWN:
                    if event.key == pygame.K_SPACE:
                        self.paused = not self.paused
                    elif event.key == pygame.K_r:
                        self.sim.reset()
                        self.paused = True
                    elif event.key == pygame.K_UP:
                        self.fps = min(30, self.fps + 1)
                    elif event.key == pygame.K_DOWN:
                        self.fps = max(1, self.fps - 1)
                    elif event.key in (pygame.K_q, pygame.K_ESCAPE):
                        running = False

            if not self.paused and self.sim.alive:
                self.sim.step()

            self.screen.fill((230, 235, 228))
            self.draw_grid()
            self.draw_agents()
            self.draw_legend()
            self.draw_panel()
            pygame.display.flip()
            self.clock.tick(self.fps)

        pygame.quit()
        sys.exit()


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    sim = Simulation(n_agents=N_AGENTS)
    renderer = Renderer(sim)
    renderer.run()